### ISSUE TITLE
Parameter inconsistence

### ISSUE THREAD

**Issue by Gregushka** [teresko/palladium#3]
Hi Martinsh!

I've made an attempt to use your library, this succeeds:
$factory = new \Palladium\Component\MapperFactory(new \PDO("omitted')), 					$tableName = "identities");

example given fails:
$registration = new \Palladium\Service\Registration($factory, $logger);
while constructor expects these:
public function __construct(Repository $repository, DataMapper $accountMapper, LoggerInterface $logger, $hashCost = self::DEFAULT_HASH_COST)
error:
Catchable fatal error: Argument 1 passed to Palladium\Service\Registration::__construct() must be an instance of Palladium\Repository\Identity, instance of Palladium\Component\MapperFactory given, called in index.php on line 12 and defined in /palladium/src/Palladium/Service/Registration.php on line 32

Any reply appreciated. Gr

**Comment by teresko** [comment]
Looks like you have accidentally installed the master branch. I was changing the interface for 2.x version, but I have not had time to update the docs and make the changelog (which is why there still is no released).

What you are seeing there is a result of moving away from direct use of factories within the services, in order to provide an option for adding "custom identities". 

If you stick with the 1.4.x version, then you should not have these errors.

**Comment by Gregushka** [comment]
Yes, this is the answer I was looking for, thank you. I'll stick to 1.4.x
